apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: espocrm-web
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: espocrm
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"