apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: espocrm
  labels:
    type: local
parameters:
  fsType: ext4
  type: gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain